config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls', namespace='library')),
]

library/urls.py
from django.urls import path
from .views import BookListView, BookCreateView, BookDeleteView, BookDetailView, BookUpdateView

app_name = 'library'

urlpatterns = [
    path('books/', BookListView.as_view(), name='books_list'),
    path('books/new/', BookCreateView.as_view(), name='book_create'),
    path('books/<int:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('books/update/<int:pk>/', BookUpdateView.as_view(), name='book_update'),
    path('books/delete/<int:pk>/', BookDeleteView.as_view(), name='book_delete'),
]

library/models.py
from django.db import models

# Create your models here.

class Author(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='Имя')
    last_name = models.CharField(max_length=150, verbose_name='Фамилия')
    birth_date = models.DateField(verbose_name='Дата рождения')

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'
        ordering = ['last_name',]


class Book(models.Model):
    title = models.CharField(max_length=200, verbose_name='Название')
    publication_date = models.DateField(verbose_name='Дата публикации')
    author = models.ForeignKey(Author, on_delete=models.CASCADE, related_name='books')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'книга'
        verbose_name_plural = 'книги'
        ordering = ['title',]

library/views.py
from IPython.core.release import author
from django.shortcuts import render
from django.urls import reverse_lazy

from .models import Book

from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView


class BookListView(ListView):
    model = Book
    template_name = 'library/books_list.html'
    context_object_name = 'books'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(publication_date__year__gt=1900)


class BookCreateView(CreateView):
    model = Book
    fields = ['title', 'publication_date', 'author']
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:books_list')


class BookDetailView(DetailView):
    model = Book
    template_name = 'library/book_detail.html'
    context_object_name = 'book'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['author_books_count'] = Book.objects.filter(author=self.object.author).count()
        return context


class BookUpdateView(UpdateView):
    model = Book
    fields = ['title', 'publication_date', 'author']
    template_name = 'library/book_form.html'
    success_url = reverse_lazy('library:books_list')


class BookDeleteView(DeleteView):
    model = Book
    template_name = 'library/book_confirm_delete.html'
    success_url = reverse_lazy('library:books_list')

library/templates/library/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Управление библиотекой{% endblock %}</title>
    <link rel="stylesheet" href="/static/css/bootstrap.min.css">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Библиотека</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="#">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Авторы</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Книги</a>
                </li>
            </ul>

        </div>

    </nav>

    <div class="container mt-5">
        {% block content %}{% endblock %}
    </div>

    <script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

library/templates/library/book_confirm_delete.html
{% extends 'library/base.html' %}

{% block title %}Удаление книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Удаление книги</h2>
<p>Вы действительно хотите удалить "{{ book.title }}"</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-danger">Подтвердить</button>
    <a href="{% url 'library:books_list' %}" class="btn btn-primary">Отменить</a>

</form>

{% endblock %}

library/templates/library/book_detail.html
{% extends 'library/base.html' %}

{% block title %}Детали книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>{{ book.title }}</h2>
<p>Автор: {{ book.author.first_name }} {{ book.author.last_name }}</p>
<p>Дата публикации: {{ book.publication_date|date:"d M Y" }}</p>
<p>Количество книг автора: {{ author_books_count }}</p>
<a href="{% url 'library:book_update' book.pk%}" class="btn btn-secondary">Редактирование</a>
<a href="{% url 'library:book_delete' book.pk%}" class="btn btn-danger">Удалить</a>
<a href="{% url 'library:books_list' %}" class="btn btn-primary">Вернуться к списку</a>

{% endblock %}

library/templates/library/book_form.html
{% extends 'library/base.html' %}

{% block title %}Форма для книги{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Форма для книги</h2>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Сохранить</button>
    <a href="{% url 'library:books_list' %}" class="btn btn-primary">Отменить</a>

</form>

{% endblock %}

library/templates/library/books_list.html
{% extends 'library/base.html' %}

{% block title %}Список книг{% endblock %}

{% block content %}
{% include 'library/header.html' %}
<h2>Список книг</h2>
<ul class="list-group">
            {% for book in books %}
                <li class="list-group-item">
                    <a href="{% url 'library:book_detail' book.pk %}">{{ book.title }}</a> - {{ book.publication_date|date:"d M Y" }} - {{ book.author.first_name }} {{ book.author.last_name }}
                </li>
            {% endfor %}
</ul>
{% endblock %}

library/templates/library/header.html
<header>
    <h1>Библиотека</h1>
    <nav>
        <a href="{% url 'library:books_list' %}">Список книг</a>
        <a href="{% url 'library:book_create' %}">Добавить книгу</a>

    </nav>

</header>